[language-server.ruff-lsp]
command = "ruff-lsp"
args = []
config = {}

[language-server.pyrefly]
command = "pyrefly"
args = ["lsp"]

[[language]]
name = "python"
auto-format = true
formatter = { command = "bash", args = ["-c", "ruff check --fix - | ruff format -"] }
language-servers = [ "pyrefly", "ruff" ]
